[2024-04-08T10:33:15.674+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:33:13.164286+00:00 [queued]>
[2024-04-08T10:33:15.681+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:33:13.164286+00:00 [queued]>
[2024-04-08T10:33:15.682+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-08T10:33:15.694+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_data_manipulation> on 2024-04-08 10:33:13.164286+00:00
[2024-04-08T10:33:15.699+0000] {standard_task_runner.py:60} INFO - Started process 77 to run task
[2024-04-08T10:33:15.702+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_data_pipeline', 'run_data_manipulation', 'manual__2024-04-08T10:33:13.164286+00:00', '--job-id', '249', '--raw', '--subdir', 'DAGS_FOLDER/my_data_pipeline.py', '--cfg-path', '/tmp/tmpd75u0ct0']
[2024-04-08T10:33:15.703+0000] {standard_task_runner.py:88} INFO - Job 249: Subtask run_data_manipulation
[2024-04-08T10:33:15.748+0000] {task_command.py:423} INFO - Running <TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:33:13.164286+00:00 [running]> on host 43a1621158a9
[2024-04-08T10:33:15.812+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_manipulation' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T10:33:13.164286+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T10:33:13.164286+00:00'
[2024-04-08T10:33:15.817+0000] {logging_mixin.py:188} INFO - An error occurred: [Errno 2] No such file or directory: '/host_data/KPI Analysis Result_Query_Result_20240325102721558(KPI Analysis Result).csv'
[2024-04-08T10:33:15.817+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T10:33:15.825+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_data_pipeline, task_id=run_data_manipulation, execution_date=20240408T103313, start_date=20240408T103315, end_date=20240408T103315
[2024-04-08T10:33:15.875+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T10:33:15.891+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
