[2024-04-08T10:28:22.943+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:28:21.433818+00:00 [queued]>
[2024-04-08T10:28:22.950+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:28:21.433818+00:00 [queued]>
[2024-04-08T10:28:22.951+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-08T10:28:22.962+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_data_manipulation> on 2024-04-08 10:28:21.433818+00:00
[2024-04-08T10:28:22.967+0000] {standard_task_runner.py:60} INFO - Started process 87 to run task
[2024-04-08T10:28:22.969+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_data_pipeline', 'run_data_manipulation', 'manual__2024-04-08T10:28:21.433818+00:00', '--job-id', '245', '--raw', '--subdir', 'DAGS_FOLDER/my_data_pipeline.py', '--cfg-path', '/tmp/tmps7dkoe46']
[2024-04-08T10:28:22.971+0000] {standard_task_runner.py:88} INFO - Job 245: Subtask run_data_manipulation
[2024-04-08T10:28:23.011+0000] {task_command.py:423} INFO - Running <TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:28:21.433818+00:00 [running]> on host 7b54c249b682
[2024-04-08T10:28:23.078+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_manipulation' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T10:28:21.433818+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T10:28:21.433818+00:00'
[2024-04-08T10:28:23.080+0000] {logging_mixin.py:188} INFO - An error occurred: name 'data_manipulation_main' is not defined
[2024-04-08T10:28:23.080+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T10:28:23.088+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_data_pipeline, task_id=run_data_manipulation, execution_date=20240408T102821, start_date=20240408T102822, end_date=20240408T102823
[2024-04-08T10:28:23.102+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T10:28:23.117+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
