[2024-04-08T10:27:40.533+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:27:37.891777+00:00 [queued]>
[2024-04-08T10:27:40.543+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:27:37.891777+00:00 [queued]>
[2024-04-08T10:27:40.545+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-08T10:27:40.558+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_data_manipulation> on 2024-04-08 10:27:37.891777+00:00
[2024-04-08T10:27:40.562+0000] {standard_task_runner.py:60} INFO - Started process 68 to run task
[2024-04-08T10:27:40.564+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_data_pipeline', 'run_data_manipulation', 'manual__2024-04-08T10:27:37.891777+00:00', '--job-id', '244', '--raw', '--subdir', 'DAGS_FOLDER/my_data_pipeline.py', '--cfg-path', '/tmp/tmpjihzwc8f']
[2024-04-08T10:27:40.566+0000] {standard_task_runner.py:88} INFO - Job 244: Subtask run_data_manipulation
[2024-04-08T10:27:40.609+0000] {task_command.py:423} INFO - Running <TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:27:37.891777+00:00 [running]> on host 7b54c249b682
[2024-04-08T10:27:40.674+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_manipulation' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T10:27:37.891777+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T10:27:37.891777+00:00'
[2024-04-08T10:27:40.675+0000] {logging_mixin.py:188} INFO - An error occurred: name 'data_manipulation_main' is not defined
[2024-04-08T10:27:40.676+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T10:27:40.684+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_data_pipeline, task_id=run_data_manipulation, execution_date=20240408T102737, start_date=20240408T102740, end_date=20240408T102740
[2024-04-08T10:27:40.738+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T10:27:40.755+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
