[2024-04-08T10:50:11.276+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:50:08.862774+00:00 [queued]>
[2024-04-08T10:50:11.282+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:50:08.862774+00:00 [queued]>
[2024-04-08T10:50:11.283+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-08T10:50:11.292+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_data_manipulation> on 2024-04-08 10:50:08.862774+00:00
[2024-04-08T10:50:11.297+0000] {standard_task_runner.py:60} INFO - Started process 69 to run task
[2024-04-08T10:50:11.300+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_data_pipeline', 'run_data_manipulation', 'manual__2024-04-08T10:50:08.862774+00:00', '--job-id', '252', '--raw', '--subdir', 'DAGS_FOLDER/my_data_pipeline.py', '--cfg-path', '/tmp/tmp4pqaldqy']
[2024-04-08T10:50:11.301+0000] {standard_task_runner.py:88} INFO - Job 252: Subtask run_data_manipulation
[2024-04-08T10:50:11.345+0000] {task_command.py:423} INFO - Running <TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-08T10:50:08.862774+00:00 [running]> on host 52c53f74aef1
[2024-04-08T10:50:11.409+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_manipulation' AIRFLOW_CTX_EXECUTION_DATE='2024-04-08T10:50:08.862774+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-08T10:50:08.862774+00:00'
[2024-04-08T10:50:11.413+0000] {logging_mixin.py:188} INFO - An error occurred: [Errno 2] No such file or directory: '/host_data/KPI Analysis Result_Query_Result_20240325102721558(KPI Analysis Result).csv'
[2024-04-08T10:50:11.413+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-08T10:50:11.420+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_data_pipeline, task_id=run_data_manipulation, execution_date=20240408T105008, start_date=20240408T105011, end_date=20240408T105011
[2024-04-08T10:50:11.474+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T10:50:11.491+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
