[2024-04-19T13:01:35.506+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-19T13:01:33.748995+00:00 [queued]>
[2024-04-19T13:01:35.513+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-19T13:01:33.748995+00:00 [queued]>
[2024-04-19T13:01:35.513+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2024-04-19T13:01:35.524+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): run_data_manipulation> on 2024-04-19 13:01:33.748995+00:00
[2024-04-19T13:01:35.529+0000] {standard_task_runner.py:60} INFO - Started process 75 to run task
[2024-04-19T13:01:35.532+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'my_data_pipeline', 'run_data_manipulation', 'manual__2024-04-19T13:01:33.748995+00:00', '--job-id', '279', '--raw', '--subdir', 'DAGS_FOLDER/my_data_pipeline.py', '--cfg-path', '/tmp/tmpbyskcjhg']
[2024-04-19T13:01:35.533+0000] {standard_task_runner.py:88} INFO - Job 279: Subtask run_data_manipulation
[2024-04-19T13:01:35.576+0000] {task_command.py:423} INFO - Running <TaskInstance: my_data_pipeline.run_data_manipulation manual__2024-04-19T13:01:33.748995+00:00 [running]> on host 75848418ef3a
[2024-04-19T13:01:35.639+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_data_pipeline' AIRFLOW_CTX_TASK_ID='run_data_manipulation' AIRFLOW_CTX_EXECUTION_DATE='2024-04-19T13:01:33.748995+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-19T13:01:33.748995+00:00'
[2024-04-19T13:01:35.640+0000] {logging_mixin.py:188} INFO - An error occurred: [Errno 2] No such file or directory: '/host_data'
[2024-04-19T13:01:35.641+0000] {python.py:202} INFO - Done. Returned value was: None
[2024-04-19T13:01:35.649+0000] {taskinstance.py:1149} INFO - Marking task as SUCCESS. dag_id=my_data_pipeline, task_id=run_data_manipulation, execution_date=20240419T130133, start_date=20240419T130135, end_date=20240419T130135
[2024-04-19T13:01:35.666+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-19T13:01:35.686+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
